# Generated by Django 2.2.3 on 2019-09-24 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20190924_0324'),
        ('blogengine', '0002_auto_20190821_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user_profile.UserProfile'),
        ),
    ]
