# Generated by Django 2.2.3 on 2019-09-24 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogengine', '0002_auto_20190821_0119'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blogengine.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
