# Generated by Django 2.2.3 on 2019-09-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20190924_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='posts',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, db_index=True, max_length=400),
        ),
    ]
