# Generated by Django 2.2.3 on 2019-09-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20190924_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=None, height_field=300, upload_to='avatar/<django.db.models.fields.related.OneToOneField>', verbose_name='Avatar', width_field=300),
            preserve_default=False,
        ),
    ]
