# Generated by Django 2.2.3 on 2019-09-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20190927_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, height_field=300, upload_to='avatar/<django.db.models.fields.related.OneToOneField>', verbose_name='Avatar', width_field=300),
        ),
    ]
