# Generated by Django 2.2.3 on 2019-10-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_auto_20191028_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='avatar/', width_field=200),
        ),
    ]
